padre(augusto,leandro).
padre(augusto,luciano).
padre(augusto,elina).
padre(augusto,julio).
padre(carlos,cecilia).
padre(carlos,marcelo).
padre(carlos,juan).
padre(carlos,laura).
padre(julioA,augusto).
padre(julioA,carlos).
padre(domingo,lucia).
madre(lastenia,augusto).
madre(lastenia,carlos).
madre(ramona,lucia).
madre(lucia,leandro).
madre(lucia,luciano).
madre(lucia,elina).
madre(lucia,julio).
hermano(augusto,carlos).
hermano(leandro,luciano).
hermano(leandro,elina).
hermano(leandro,julio).
hermano(luciano,leandro).
hermano(luciano,elina).
hermano(luciano,julio).
hermano(julio,leandro).
hermano(julio,luciano).
hermano(julio,elina).
hermano(elina,leandro).
hermano(elina,luciano).
hermano(elina,julio).
tio(carlos,leandro).
tio(carlos,luciano).
tio(carlos,elina).
tio(carlos,julio).
tio(augusto,cecilia).
tio(augusto,marcelo).
tio(augusto,juan).
tio(augusto,laura).
abuela(A,B):-madre(A,C),(padre(C,B);madre(C,B)).
abuelo(A,B):-padre(A,C),(madre(C,B);padre(C,B)).
primo(A,B):-tio(C,A),padre(C,B),not(A=B).